### ISSUE TITLE
Manual install docu

### ISSUE THREAD

**Issue by ain** [tutumcloud/tutum-cli#60]
For users discouraging HomeBrew and preferring MacPorts, there's currently no way to install. 

I think it'd make sense to update documentation for manual build?

**Comment by tifayuki** [comment]
Hi ain

I will take a look at MacPorts.
In the meanwhile, you can still use `pip install tutum` on your mac, I think.

**Comment by ain** [comment]
@tifayuki tried that. Succeeds, but installs tutum incorrectly __since python27 runs from MacPorts__ so the path ends up being:

    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/tutum

So for MacPorts users the current workaround is rather simple:

    sudo ln -s /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/tutum /opt/local/bin/tutum

**Comment by ain** [comment]
Nevertheless, I think you need a fix here.

**Comment by ain** [comment]
My above workaround isn't really working out. There's an error on pushing the image (not sure if this is related to the current issue, but seems to):
```
$ tutum image push dockerhello_web_1
Traceback (most recent call last):
  File "/opt/local/bin/tutum", line 9, in <module>
    load_entry_point('tutum==0.14.0', 'console_scripts', 'tutum')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tutumcli/tutum_cli.py", line 259, in main
    dispatch_cmds(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tutumcli/tutum_cli.py", line 172, in dispatch_cmds
    commands.image_push(args.name, args.public)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tutumcli/commands.py", line 764, in image_push
    docker_client = utils.get_docker_client()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tutumcli/utils.py", line 95, in get_docker_client
    raise DockerNotFound("Cannot connect to docker (is it running?)")
tutumcli.exceptions.DockerNotFound: Cannot connect to docker (is it running?)
```
With:
```
$ boot2docker status
running
```
Platform:
```
$ boot2docker version
Boot2Docker-cli version: v1.5.0
Git commit: ccd9032
$ docker-compose --version
docker-compose 1.1.0
Mac OS X 10.10.3
```

**Comment by tifayuki** [comment]
Did you set the environment variable?
```
DOCKER_TLS_VERIFY
DOCKER_CERT_PATH
DOCKER_HOST
```

**Comment by ain** [comment]
ENV is:

    export DOCKER_TLS_VERIFY=1
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH=~/.boot2docker/certs/boot2docker-vm

**Comment by aytawn** [comment]
Was this ever solved? I'm debating whether to use Tutum but the requirement that I ditch MacPorts is a deal breaker.
