### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by paurullan** [tutumcloud/tutum-cli#65]
This package does not seem to be python3 compatible, is it?

```
(project)~$ tutum
Traceback (most recent call last):
  File "/home/paurullan/.virtualenvs/project/bin/tutum", line 7, in <module>
    from tutumcli.tutum_cli import main
  File "/home/paurullan/.virtualenvs/project/lib/python3.4/site-packages/tutumcli/tutum_cli.py", line 11, in <module>
    from tutumcli import commands
  File "/home/paurullan/.virtualenvs/project/lib/python3.4/site-packages/tutumcli/commands.py", line 8, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'
```

**Comment by roll** [comment]
:+1:
