### ISSUE TITLE
Can't run tutum on Ubuntu 15.10? pkg_resources.DistributionNotFound: requests==2.5.3

### ISSUE THREAD

**Issue by RdeWilde** [tutumcloud/tutum-cli#67]
Gives me an error `pkg_resources.DistributionNotFound: requests==2.5.3`

```
me@desktop:~$ sudo -H pip install tutum
[sudo] password for me: 
Collecting tutum
  Using cached tutum-0.15.1.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): python-tutum==0.15.1.1 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): ago==0.0.6 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.2 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): tabulate==0.7.2 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): docker-py==1.1.0 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): requests==2.5.3 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): future==0.14.3 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): websocket-client==0.11.0 in /usr/local/lib/python2.7/dist-packages (from tutum)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from python-dateutil==2.2->tutum)
Installing collected packages: tutum
  Running setup.py install for tutum
Successfully installed tutum-0.15.1.1
```

```
me@desktop:~$ tutum
Traceback (most recent call last):
  File "/usr/local/bin/tutum", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in <module>
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: requests==2.5.3
```

```
me@desktop:~$ pip -V
pip 7.0.3 from /usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg (python 2.7)
```

```
me@desktop:~$ python -V
Python 2.7.9
```

```
me@desktop:~$ uname -a
Linux desktop 3.19.0-18-generic #18-Ubuntu SMP Tue May 19 18:31:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tifayuki** [comment]
your log shows `Requirement already satisfied (use --upgrade to upgrade): requests==2.5.3 in /usr/local/lib/python2.7/dist-packages (from tutum)`

Can you try `pip freeze` to see if requests 2.5.3 is installed in your system? And try to manually install request by using `pip install requests==2.5.3`

**Comment by RdeWilde** [comment]
ne@desktop:~$ pip freeze
adium-theme-ubuntu==0.3.4
ago==0.0.6
apt-xapian-index==0.46
beautifulsoup4==4.3.2
ccsm==0.9.12.1
characteristic==0.1.0
chardet==2.3.0
command-not-found==0.3
compizconfig-python==0.9.12.1
debtagshw==0.1
defer==1.0.6
dirspec==13.10
docker-py==1.1.0
duplicity==0.7.1
ecdsa==0.11
future==0.14.3
html5lib==0.999
httplib2==0.9
idna==0.9
lockfile==0.8
lxml==3.4.2
oauthlib==0.6.1
oneconf==0.3.7
PAM==0.4.2
paramiko==1.15.1
Pillow==2.7.0
piston-mini-client==0.7.5
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycrypto==2.6.1
pycups==1.9.72
pycurl==7.19.5
pygobject==3.14.0
pyOpenSSL==0.13.1
pyserial==2.6
python-apt===0.9.3.11build1
python-dateutil==2.2
python-debian==0.1.22
python-tutum==0.15.1.1
pyxdg==0.25
PyYAML==3.10
requests==2.5.3           <<<<<<<<<<<
service-identity==1.0.0
sessioninstaller==0.0.0
six==1.9.0
software-center-aptd-plugins==0.0.0
system-service==0.1.6
tabulate==0.7.2
tutum==0.15.1.1
Twisted-Core==14.0.2
Twisted-Web==14.0.2
unity-launcher-folders==14.9.4
unity-lens-photos==1.0
websocket-client==0.11.0
xdiagnose==3.7.2
zope.interface==4.1.1
```

**Comment by tifayuki** [comment]
Can you try the solution mentioned here (https://github.com/chrippa/livestreamer/issues/384)?

`pip install --upgrade --force-reinstall requests tutum`
or
`easy_install --upgrade requests`

**Comment by RdeWilde** [comment]
@tifayuki 
```
me@desktop:~$ sudo -H pip install --upgrade --force-reinstall requests tutum
Collecting requests
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 601kB/s 
Collecting tutum
  Using cached tutum-0.15.1.1.tar.gz
Collecting python-tutum==0.15.1.1 (from tutum)
  Using cached python-tutum-0.15.1.1.tar.gz
Collecting PyYAML==3.10 (from tutum)
  Using cached PyYAML-3.10.tar.gz
Collecting ago==0.0.6 (from tutum)
  Using cached ago-0.0.6.tar.gz
Collecting python-dateutil==2.2 (from tutum)
  Using cached python-dateutil-2.2.tar.gz
Collecting tabulate==0.7.2 (from tutum)
  Using cached tabulate-0.7.2.tar.gz
Collecting docker-py==1.1.0 (from tutum)
  Using cached docker-py-1.1.0.tar.gz
Collecting future==0.14.3 (from tutum)
  Using cached future-0.14.3.tar.gz
Collecting websocket-client==0.11.0 (from tutum)
  Using cached websocket-client-0.11.0.tar.gz
Collecting six (from python-dateutil==2.2->tutum)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: requests, future, websocket-client, python-tutum, PyYAML, ago, six, python-dateutil, tabulate, docker-py, tutum
  Found existing installation: requests 2.5.3
    Uninstalling requests-2.5.3:
      Successfully uninstalled requests-2.5.3
  Found existing installation: future 0.14.3
    Uninstalling future-0.14.3:
      Successfully uninstalled future-0.14.3
  Running setup.py install for future
  Found existing installation: websocket-client 0.11.0
    Uninstalling websocket-client-0.11.0:
      Successfully uninstalled websocket-client-0.11.0
  Running setup.py install for websocket-client
  Found existing installation: python-tutum 0.15.1.1
    Uninstalling python-tutum-0.15.1.1:
      Successfully uninstalled python-tutum-0.15.1.1
  Running setup.py install for python-tutum
  Found existing installation: PyYAML 3.10
    Uninstalling PyYAML-3.10:
      Successfully uninstalled PyYAML-3.10
  Running setup.py install for PyYAML
  Found existing installation: ago 0.0.6
    Uninstalling ago-0.0.6:
      Successfully uninstalled ago-0.0.6
  Running setup.py install for ago
  Found existing installation: six 1.9.0
    Uninstalling six-1.9.0:
      Successfully uninstalled six-1.9.0
  Found existing installation: python-dateutil 2.2
    Uninstalling python-dateutil-2.2:
      Successfully uninstalled python-dateutil-2.2
  Running setup.py install for python-dateutil
  Found existing installation: tabulate 0.7.2
    Uninstalling tabulate-0.7.2:
      Successfully uninstalled tabulate-0.7.2
  Running setup.py install for tabulate
  Found existing installation: docker-py 1.1.0
    Uninstalling docker-py-1.1.0:
      Successfully uninstalled docker-py-1.1.0
  Running setup.py install for docker-py
  Found existing installation: tutum 0.15.1.1
    Uninstalling tutum-0.15.1.1:
      Successfully uninstalled tutum-0.15.1.1
  Running setup.py install for tutum
Successfully installed PyYAML-3.10 ago-0.0.6 docker-py-1.1.0 future-0.14.3 python-dateutil-2.2 python-tutum-0.15.1.1 requests-2.7.0 six-1.9.0 tabulate-0.7.2 tutum-0.15.1.1 websocket-client-0.11.0
```

Still same error though.

**Comment by tifayuki** [comment]
Sorry, forget to say that you need to fix the version 

pip install --upgrade --force-reinstall requests==2.5.3 tutum
easy_install --upgrade requests==2.5.3

**Comment by RdeWilde** [comment]
@tifayuki Same result/error. Though I'm running 2.5.3 again as before.

**Comment by RdeWilde** [comment]
Fixed using ...
